# add the linters you want stickler to use for this project
linters:
  stylelint:
    # indicate where is the config file for stylelint
<<<<<<< HEAD
    config: "stylelint.config.js"
=======
    config: 'stylelint.config.js'

>>>>>>> e6328e3f04bf1207f334b133f6c36c8dff19e216
# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

# find full documentation here: https://stickler-ci.com/docs
